ALTER TABLE IMPOR.ITEM_UNIDAD
 DROP PRIMARY KEY CASCADE;

DROP TABLE IMPOR.ITEM_UNIDAD CASCADE CONSTRAINTS;

CREATE TABLE IMPOR.ITEM_UNIDAD
(
  MITEM_CODIGO                NUMBER(10)        NOT NULL,
  ITEM_UND_STOCK_TOTAL        NUMBER(15,3)      DEFAULT 0                     NOT NULL,
  UNIDAD_CODIGO               CHAR(3 BYTE)      NOT NULL,
  ITEM_UND_EMPAQUE_SERIE      CHAR(1 BYTE),
  ITEM_UND_ESTADO             CHAR(1 BYTE)      DEFAULT '0',
  ITEM_UND_DE_LLEGADA         CHAR(1 BYTE),
  ITEM_UND_BASE_CONVER        CHAR(1 BYTE),
  ITEM_UND_FACTOR             NUMBER(15,6),
  ITEM_UND_NRO_TOTAL_BOBINAS  NUMBER(15,3)      DEFAULT 0                     NOT NULL,
  ITEM_UND_PRECIO_LISTA       NUMBER(20,6),
  ITEM_UND_TIPO_ORIGEN        CHAR(1 BYTE),
  ITEM_UND_EN_LISTA_PRECIOS   CHAR(1 BYTE)      DEFAULT '0',
  ITEM_UND_FACTOR_REAL        NUMBER(15,6),
  ITEM_UND_STOCK_MAQ          NUMBER(15,3)      DEFAULT 0,
  GENER_SECUENCIAL            NUMBER(10),
  ITEM_UND_FEC_COSTO          DATE,
  ITEM_UND_COSTO_OBLIG        CHAR(1 BYTE),
  ITEM_UND_FEC_ULT_MODIF      DATE,
  ITEM_UND_COSTO_SOL          NUMBER(20,6),
  ITEM_UND_COSTO_DOL          NUMBER(20,6),
  ITEM_UND_FEC_GRAB           DATE              DEFAULT SYSDATE
)
TABLESPACE TEALMACEN
PCTUSED    0
PCTFREE    20
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1032K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN IMPOR.ITEM_UNIDAD.ITEM_UND_EMPAQUE_SERIE IS 'B: BOBINA
C: CAJA
P: PALETA
NULL : NO SERIADO
';

COMMENT ON COLUMN IMPOR.ITEM_UNIDAD.ITEM_UND_DE_LLEGADA IS 'Una X indica que es la unidad de llegada por defecto';

COMMENT ON COLUMN IMPOR.ITEM_UNIDAD.ITEM_UND_BASE_CONVER IS 'Una X indica que la unidad será la base para las converisones.';

COMMENT ON COLUMN IMPOR.ITEM_UNIDAD.ITEM_UND_FACTOR IS 'Indica el valor por el que hay que multiplicar para obtener la unidad base de conversión. No es necesaria para unidades interconvertibles.';

COMMENT ON COLUMN IMPOR.ITEM_UNIDAD.ITEM_UND_PRECIO_LISTA IS 'Precio de lista';

COMMENT ON COLUMN IMPOR.ITEM_UNIDAD.ITEM_UND_TIPO_ORIGEN IS 'M: Mercadería
P: Producto terminado
R: Materia Prima
I : Insumo
S: Servicio';

COMMENT ON COLUMN IMPOR.ITEM_UNIDAD.ITEM_UND_EN_LISTA_PRECIOS IS '0: No se encuentra en el reporte de lista de precios
1: Sí aparece en el reporte de lista de precios';

COMMENT ON COLUMN IMPOR.ITEM_UNIDAD.ITEM_UND_COSTO_OBLIG IS 'Si esta en 1, se fuerza a tomar el costo digitado.';

COMMENT ON COLUMN IMPOR.ITEM_UNIDAD.ITEM_UND_COSTO_SOL IS 'Costo unitario, usado cuando el Item no tiene asignado el costos en la Compra Local o Importacion';

COMMENT ON COLUMN IMPOR.ITEM_UNIDAD.ITEM_UND_COSTO_DOL IS 'Costo unitario, usado cuando el Item no tiene asignado el costos en la Compra Local o Importacion';


CREATE INDEX IMPOR.XIE1ITEM_ORIGEN ON IMPOR.ITEM_UNIDAD
(MITEM_CODIGO, ITEM_UND_TIPO_ORIGEN)
LOGGING
TABLESPACE TEALMA_IN
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          400K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IMPOR.XIE1ITEM_UNIDAD ON IMPOR.ITEM_UNIDAD
(ITEM_UND_BASE_CONVER, UNIDAD_CODIGO)
LOGGING
TABLESPACE TEALMA_IN
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          400K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX IMPOR.XIE2ITEM_UNIDAD_ORIGEST ON IMPOR.ITEM_UNIDAD
(ITEM_UND_TIPO_ORIGEN, ITEM_UND_ESTADO)
LOGGING
TABLESPACE TEALMA_IN
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          200K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER IMPOR.TI_ITEM_UNIDAD
BEFORE INSERT ON IMPOR.ITEM_UNIDAD FOR EACH ROW
DECLARE
LINEA CHAR(3);
BEGIN
 SELECT MITEM.LINEA_CODIGO INTO LINEA FROM MITEM WHERE MITEM.MITEM_CODIGO = :NEW.MITEM_CODIGO;
 IF LINEA = '015' OR LINEA = '016' OR LINEA = '017' OR LINEA = '018' OR LINEA = '019' OR LINEA = '021' THEN
	IF :NEW.item_und_tipo_origen <> 'W' THEN
		-- Si no era Muestra Proveedor -> convierte a Insumo
		:NEW.ITEM_UND_TIPO_ORIGEN := 'I';
	END IF;
 END IF;
EXCEPTION
 WHEN TOO_MANY_ROWS OR NO_DATA_FOUND THEN
 raise_application_error(-20999,'... Error, No encontrado el Item en MITEM');
END;
/


CREATE OR REPLACE TRIGGER IMPOR.TU_ITEM_UNIDAD
BEFORE UPDATE ON IMPOR.ITEM_UNIDAD FOR EACH ROW
DECLARE
LINEA CHAR(3);
BEGIN
 SELECT MITEM.LINEA_CODIGO INTO LINEA FROM MITEM WHERE MITEM.MITEM_CODIGO = :NEW.MITEM_CODIGO;
 IF LINEA = '015' OR LINEA = '016' OR LINEA = '017' OR LINEA = '018' OR LINEA = '019' OR LINEA = '021' THEN
	IF :NEW.item_und_tipo_origen <> 'W' THEN
		-- Si no era Muestra Proveedor -> convierte a Insumo
		:NEW.ITEM_UND_TIPO_ORIGEN := 'I';
	END IF;
 END IF;
EXCEPTION
 WHEN TOO_MANY_ROWS OR NO_DATA_FOUND THEN
 raise_application_error(-20999,'... Error, No encontrado el Item en MITEM');
END;
/


ALTER TABLE IMPOR.ITEM_UNIDAD ADD (
  PRIMARY KEY
 (MITEM_CODIGO, UNIDAD_CODIGO)
    USING INDEX 
    TABLESPACE TEALMACEN
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          400K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE IMPOR.ITEM_UNIDAD ADD (
  CONSTRAINT R_985 
 FOREIGN KEY (GENER_SECUENCIAL) 
 REFERENCES IMPOR.GENERICO (GENER_SECUENCIAL),
  FOREIGN KEY (MITEM_CODIGO) 
 REFERENCES IMPOR.MITEM (MITEM_CODIGO),
  FOREIGN KEY (UNIDAD_CODIGO) 
 REFERENCES IMPOR.MUNIDAD (UNIDAD_CODIGO),
  FOREIGN KEY (ITEM_UND_TIPO_ORIGEN) 
 REFERENCES IMPOR.TORIGEN (ORIGEN_CODIGO),
  FOREIGN KEY (ITEM_UND_EMPAQUE_SERIE) 
 REFERENCES IMPOR.TSERIADO (TSER_CODIGO));

GRANT SELECT ON IMPOR.ITEM_UNIDAD TO MCODE;
