DROP TABLE IMPOR.INVENTARIO_BOBINAS CASCADE CONSTRAINTS;

CREATE TABLE IMPOR.INVENTARIO_BOBINAS
(
  FECHA_GRABACION    DATE,
  BOBI_CODIGO        NUMBER(10),
  BOBI_SERIE         CHAR(3 BYTE),
  UBIFISI_CODIGO     CHAR(8 BYTE),
  UBI_ALMACEN_SERIE  CHAR(3 BYTE),
  UBI_SUBALMNUM      CHAR(3 BYTE),
  UNIDAD_CODIGO      CHAR(3 BYTE),
  USU_ULT_MODIF      VARCHAR2(20 BYTE),
  BOBI_PESO          NUMBER(15,3),
  BOBI_PESO_STOCK    NUMBER(15,3),
  MITEM_CODIGO       NUMBER(10),
  ALMACEN_SERIE      CHAR(3 BYTE),
  NUMERO_INVENTARIO  NUMBER(8),
  HPC_SECUENCIAL     NUMBER(10),
  BOBI_ESTADO        CHAR(1 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT INSERT, SELECT, UPDATE ON IMPOR.INVENTARIO_BOBINAS TO MCODE;
