ALTER TABLE IMPOR.HPROGRAMACION
 DROP PRIMARY KEY CASCADE;

DROP TABLE IMPOR.HPROGRAMACION CASCADE CONSTRAINTS;

CREATE TABLE IMPOR.HPROGRAMACION
(
  HPROG_CODIGO                NUMBER(10)        NOT NULL,
  PLANTA_SERIE                CHAR(3 BYTE)      NOT NULL,
  CLIENTE_CODIGO              CHAR(6 BYTE),
  PROCESO_CODIGO              NUMBER(10),
  MAQUINA_CODIGO              NUMBER(10)        DEFAULT NULL,
  HPROG_ORDEN                 NUMBER(4),
  DESARROLLO_CODIGO           CHAR(4 BYTE),
  PINNONES_CODIGO             CHAR(4 BYTE),
  HPROG_ESTADO                CHAR(1 BYTE)      DEFAULT '0'                   NOT NULL,
  HPROG_KILOS_NETOS           NUMBER(10,2),
  HPROG_IMP_CANT_COLORES      NUMBER(2),
  MAQUINA_VELOCIDAD           NUMBER(4),
  HPROG_OBSERVACIONES         NVARCHAR2(200),
  HPROG_METROS                NUMBER(12,2),
  HPROG_HORAS_CORRIENDO       NUMBER(6,2),
  HPROG_HORAS_PARADAS         NUMBER(6,2),
  HPROG_HORAS_TOTALES         NUMBER(6,2),
  HPROG_IMP_PORC_REFILE       NUMBER(6,3),
  HPROG_HORAS_CAMBIO          NUMBER(6,2),
  HPROG_LAM_PORC_REFILE       NUMBER(6,3),
  USER_NEW                    VARCHAR2(20 BYTE),
  USER_EDIT                   VARCHAR2(20 BYTE),
  DATE_NEW                    DATE,
  DATE_EDIT                   DATE,
  FECHA_PROGRAMACION_INICIO   DATE,
  FECHA_PROGRAMACION_FIN      DATE,
  HPROG_IMP_GRJE_IMPR         NUMBER(10,2),
  HPROG_IMP_FORMAS_ANCHO      NUMBER(6,2),
  HPROG_LAM_GRJE_ADH          NUMBER(10,2),
  HPROG_LAM_GRJE_TOTAL        NUMBER(10,2),
  HPROG_LAM_ANCHO_UTIL        NUMBER(10,2),
  HPROG_ESTADO_MOTIVO         VARCHAR2(100 BYTE),
  HPROG_LAM_KILOS_LAMINACION  NUMBER(10,2),
  HPROG_LAM_KILOS_LAMINANTE   NUMBER(10,2),
  HPROG_PROGRAMADO            CHAR(1 BYTE)      DEFAULT '0',
  HPROG_CORTE_FINAL           NUMBER(6,2),
  SUBPROCESO_CODIGO           NUMBER(10),
  HPROG_HORAS_TIRAJE          NUMBER(6,2),
  HPROG_HORAS_CORRECCION      NVARCHAR2(8)      DEFAULT '(+)00:00',
  HPROG_CONTAINER             VARCHAR2(100 BYTE),
  HPROG_EXT_ANCHO             NUMBER(10,2),
  HPROG_EXT_GRJE              NUMBER(10,2),
  HPROG_EXT_PEBD              VARCHAR2(20 BYTE),
  HPROG_EXT_AVANCE            NUMBER(10,2),
  HPROG_LANZADO               CHAR(1 BYTE)      DEFAULT '0',
  HPROG_VISTO_BUENO           VARCHAR2(100 BYTE),
  HPROG_IMP_GRJE_MATERIAL     NUMBER(15,3),
  HPROG_IMP_GRJE_TINTA        NUMBER(15,3),
  HPROG_IMP_GRJE              NUMBER(15,3),
  HPROG_KILOS_INS_LIQUIDO     NUMBER(15,3)      DEFAULT 0,
  HPROG_KILOS_PROD_PROCESO    NUMBER(15,3)      DEFAULT 0,
  HPROG_KILOS_MERMA           NUMBER(15,3)      DEFAULT 0,
  OP_PADRE                    NUMBER(10),
  EST_PREPROG                 NUMBER(1)         DEFAULT 0                     NOT NULL,
  HPROG_BARN_GRJE             NUMBER(15,3),
  HPROG_BARN_GRJE_TOTAL       NUMBER(15,3),
  HPROG_SETUP                 NUMBER(4),
  HPROG_METROS_ZIPP           NUMBER(12,2),
  HPROG_MOTIVO                VARCHAR2(100 BYTE),
  HPROG_KILOS_OUT             NUMBER(10,2),
  HPROG_EXT_RELA_SOPLADO      NUMBER(10,2),
  HPROG_EXT_KG_HR             NUMBER(10,2),
  EXT_OT_PT                   VARCHAR2(50 BYTE),
  EXT_ITEM_PT                 VARCHAR2(50 BYTE)
)
TABLESPACE TEPRODUCCION
PCTUSED    0
PCTFREE    20
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          200K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN IMPOR.HPROGRAMACION.HPROG_KILOS_MERMA IS 'Kgrs de merma por proceso programado';

COMMENT ON COLUMN IMPOR.HPROGRAMACION.HPROG_KILOS_PROD_PROCESO IS 'Kgrs de productos en proceso a programar';

COMMENT ON COLUMN IMPOR.HPROGRAMACION.HPROG_KILOS_INS_LIQUIDO IS 'Kgrs de insumo liquido a programar(tintas, adhesivos, barniz)';


CREATE OR REPLACE TRIGGER IMPOR.DBOBINA_UPD
  AFTER UPDATE ON IMPOR.HPROGRAMACION   FOR EACH ROW
WHEN (
new.HPROG_ESTADO='3' AND new.PROCESO_CODIGO IN (1, 7, 8, 86)
      )
BEGIN

        UPDATE DRESERVA_MATERIALES SET 
        DRESERVA_ESTADO='X'
        WHERE HPROG_CODIGO=:NEW.HPROG_CODIGO AND PROCESO_CODIGO=:NEW.PROCESO_CODIGO AND DRESERVA_ESTADO IN ('0', '1', '2');

END;
/


DROP PUBLIC SYNONYM HPROGRAMACION;

CREATE PUBLIC SYNONYM HPROGRAMACION FOR IMPOR.HPROGRAMACION;


ALTER TABLE IMPOR.HPROGRAMACION ADD (
  PRIMARY KEY
 (HPROG_CODIGO, PLANTA_SERIE, PROCESO_CODIGO)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE IMPOR.HPROGRAMACION ADD (
  FOREIGN KEY (PROCESO_CODIGO) 
 REFERENCES IMPOR.PROCESO (PROCESO_CODIGO),
  FOREIGN KEY (MAQUINA_CODIGO) 
 REFERENCES IMPOR.MAQUINA (MAQUINA_CODIGO),
  FOREIGN KEY (CLIENTE_CODIGO) 
 REFERENCES IMPOR.CLIENTE_PROVEEDOR (CLIENTE_CODIGO));
